/*
  archive_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/{archive_format}{/ref}"
  archived: false
  assignees_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/assignees{/user}"
  blobs_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/git/blobs{/sha}"
  branches_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/branches{/branch}"
  clone_url: "https://github.com/MichaelDimmitt/angular-component.git"
  collaborators_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/collaborators{/collaborator}"
  comments_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/comments{/number}"
  commits_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/commits{/sha}"
  compare_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/compare/{base}...{head}"
  contents_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/contents/{+path}"
  contributors_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/contributors"
  created_at: "2020-05-19T05:18:41Z"
  default_branch: "master"
  deployments_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/deployments"
  description: "Code for Advanced Angular Components Programming Talk."
  disabled: false
  downloads_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/downloads"
  events_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/events"
  fork: false
  forks: 0
  forks_count: 0
  forks_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/forks"
  full_name: "MichaelDimmitt/angular-component"
  git_commits_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/git/commits{/sha}"
  git_refs_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/git/refs{/sha}"
  git_tags_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/git/tags{/sha}"
  git_url: "git://github.com/MichaelDimmitt/angular-component.git"
  has_downloads: true
  has_issues: true
  has_pages: false
  has_projects: true
  has_wiki: true
  homepage: ""
  hooks_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/hooks"
  html_url: "https://github.com/MichaelDimmitt/angular-component"
  id: 265152363
  issue_comment_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/issues/comments{/number}"
  issue_events_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/issues/events{/number}"
  issues_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/issues{/number}"
  keys_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/keys{/key_id}"
  labels_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/labels{/name}"
  language: "TypeScript"
  languages_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/languages"
  license: null
  merges_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/merges"
  milestones_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/milestones{/number}"
  mirror_url: null
  name: "angular-component"
  node_id: "MDEwOlJlcG9zaXRvcnkyNjUxNTIzNjM="
  notifications_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/notifications{?since,all,participating}"
  open_issues: 0
  open_issues_count: 0
  owner: {login: "MichaelDimmitt", id: 11463275, node_id: "MDQ6VXNlcjExNDYzMjc1", avatar_url: "https://avatars1.githubusercontent.com/u/11463275?v=4", gravatar_id: "", …}
  private: false
  pulls_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/pulls{/number}"
  pushed_at: "2020-05-19T05:18:49Z"
  releases_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/releases{/id}"
  size: 370
  ssh_url: "git@github.com:MichaelDimmitt/angular-component.git"
  stargazers_count: 0
  stargazers_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/stargazers"
  statuses_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/statuses/{sha}"
  subscribers_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/subscribers"
  subscription_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/subscription"
  svn_url: "https://github.com/MichaelDimmitt/angular-component"
  tags_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/tags"
  teams_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/teams"
  trees_url: "https://api.github.com/repos/MichaelDimmitt/angular-component/git/trees{/sha}"
  updated_at: "2020-05-19T05:54:04Z"
  url: "https://api.github.com/repos/MichaelDimmitt/angular-component"
  watchers: 0
  watchers_count: 0
*/